### ISSUE TITLE
Large Objects (feature request)

### ISSUE THREAD

**Issue by avkhozov** [kraih/mojo-pg#11]
Are there any plans to create a interface for postgres large object?

**Comment by kraih** [comment]
No plans.

**Comment by avkhozov** [comment]
A patch would be welcome? :)

**Comment by kraih** [comment]
Don't know, never used that part of the API.

**Comment by shadowcat-mst** [comment]
@avkhozov Perhaps if you proposed an interface or at least a feature set it would be easier to figure out if it's going to be a good idea?

**Comment by avkhozov** [comment]
I think access to large object data (``Mojo::Pg::LO`` or ``Mojo::Pg::File``) must have an interface similar to ``IO::File``. Thus it can be used in conjunction with ``Mojo::Asset::File`` and conveniently serve static files using ``reply->asset`` helper or using ``slurp`` to processing data in memory.

**Comment by avkhozov** [comment]
Some interfaces in ruby:
https://github.com/diogob/carrierwave-postgresql/blob/master/lib/carrierwave/storage/postgresql_lo.rb
http://deveiate.org/code/pg/PG/Connection.html#method-i-lo_close

**Comment by shadowcat-mst** [comment]
The first one appears to be rails-specific and just being -just- file-like enough for an upload handler.

The second one appears to be entirely equivalent to calling the originally existing DBD::Pg methods.

Have you looked at the DBD::Pg API that already exists? Given that, what, specifically, are you proposing Mojo::Pg provides that you don't already have?

"I think X must have an interface like Y" needs to be backed up with sufficient use cases to justify the extra complexity, especially given there's an already-extant interface you could, y'know, just call :)
