### ISSUE TITLE
Mojo::Pg::Results error during global destruction

### ISSUE THREAD

**Issue by nnutter** [kraih/mojo-pg#12]
One of my Mojo::PgX::Cursor tests is consistently producing an error:

```
Can't call method "FETCH" on an undefined value at .../Mojo/Pg/Results.pm line 13, <DATA> line 2231 during global destruction.
```

And on occasion another Mojo::PgX::Cursor test does as well.

I'm wondering if Mojo::Pg::Results should get a,

```
return if defined(${^GLOBAL_PHASE}) && ${^GLOBAL_PHASE} eq 'DESTRUCT';
```

like Mojo::Pg::Database did in a8dbeab671ec2e4c980637beb3d7627fc74f74f6.

**Comment by kraih** [comment]
Hard to say without a test case.
