### ISSUE TITLE
Expand hstore columns.

### ISSUE THREAD

**Issue by jkramer** [kraih/mojo-pg#13]
Please expand the values of columns of type hstore (simple key/value assignments) in Mojo::Pg::Results::expand as well. Currently the a scalar with the text representation is returned.

http://www.postgresql.org/docs/current/static/hstore.html

**Comment by kraih** [comment]
Are there any reasons to use `hstore` over `jsonb` these days?

**Comment by jkramer** [comment]
> Are there any reasons to use hstore over jsonb these days?

Nothing really, but it'd be convenient for existing databases. However I just figured out that I can just cast the hstore column to ::json to get it expanded.
