### ISSUE TITLE
Allow passwordless authentication

### ISSUE THREAD

**Issue by oalders** [kraih/mojo-pg#14]
I'm trying to integrate Minion with MetaCPAN.  Our Pg is set up to authenticate without a password.  However, when I try to get started, I get tripped up by this line, which is verifying the presence of a password:  https://metacpan.org/source/SRI/Mojo-Pg-2.23/lib/Mojo/Pg.pm#L80

What I've got is `{ Pg => 'postgresql://vagrant@localhost/minion_queue' }`

Is there some other way to express this for passwordless auth?

**Comment by kraih** [comment]
I don't see anything verifying a password.

**Comment by oalders** [comment]
The error is `Can't load application from file "/home/vagrant/metacpan-api/bin/queue.pl": DBI connect('dbname=minion_queue;host=localhost','',...) failed: fe_sendauth: no password supplied at /home/vagrant/carton/metacpan-api/lib/perl5/Mojo/Pg.pm line 80.`

Should have looked more closely as it's an error from DBI.

**Comment by tsibley** [comment]
`fe_sendauth:` implies an error from the Pg server or the Pg client lib.
