### ISSUE TITLE
Inheritance ability

### ISSUE THREAD

**Issue by mche** [kraih/mojo-pg#26]
* Mojo::Pg version: 2.28
* perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux

### Steps to reproduce the behavior
I try to extend and expand **Mojo::Pg** by `use Mojo::Base 'Mojo::Pg;`.
And I try also extend **Mojo::Pg::Database** and **Mojo::Pg::Results**.

### Expected behavior
* I would like that the `$pg->db` will produce my inherit database class object.
* I would like that the `$db->query` will produce my inherit result class object for blocking query.
* I would like that the result object passed to callback for non-blocking query will be my inherit result class object.
* I would like that the secondary modules **Mojo::Pg::Migrations** and **Mojo::Pg::PubSub** will load on demand.

### Actual behavior
At moment classnames **Mojo::Pg::Database** and **Mojo::Pg::Results** has hard coded places.

Here my  [patching](https://github.com/kraih/mojo-pg/compare/master...mche:master)

**Comment by mche** [comment]
Also, the [Mojo::SQLite](https://metacpan.org/pod/Mojo::SQLite) did made dirty copy/paste of your module code. He couldn't inheritance.

**Comment by kraih** [comment]
Thanks, the feature has been added.

**Comment by mche** [comment]
have a nice
